### ISSUE TITLE
Button will not remove after click

### ISSUE THREAD

**Issue by ryadaj** [shabegom/buttons#28]
This plugin is amazing! Thank you so much. 

Just having trouble getting the button to remove after clicking. Here is the snippet:

```button
name Monday Checklist
type prepend template
action Template Monday Checklist
remove true
```

It inserts the template but doesn't remove, it just moves to the bottom of the template.

Sorry if there is an obvious solution—I'm not a tech savvy person haha.

Thanks for all your hard work!

![Screen Shot 2021-05-06 at 10 21 05 PM](https://user-images.githubusercontent.com/82765301/117388816-5d27bc00-aeb9-11eb-851d-7aff294369ef.png)

![Screen Shot 2021-05-06 at 10 20 46 PM](https://user-images.githubusercontent.com/82765301/117388786-51d49080-aeb9-11eb-872a-5d66bead2f80.png)

**Comment by ryadaj** [comment]
Feel free to roll this into the Double Button issue as I'm also following that hoping to remove two buttons once I can wrap my head around it

**Comment by shabegom** [comment]
I've just pushed an update that might fix this error. Please update to 0.3.8 and confirm. Thanks!

**Comment by ryadaj** [comment]
Thanks for your speed! Now when I click a button, only one is removed and then there is code blocks at the bottom
<img width="1758" alt="Screen Shot 2021-05-07 at 3 30 26 PM" src="https://user-images.githubusercontent.com/82765301/117499491-5052a900-af49-11eb-9beb-621a5048386a.png">
<img width="1758" alt="Screen Shot 2021-05-07 at 3 30 36 PM" src="https://user-images.githubusercontent.com/82765301/117499498-5183d600-af49-11eb-9ae9-2c105c4fbf66.png">
<img width="1758" alt="Screen Shot 2021-05-07 at 3 30 41 PM" src="https://user-images.githubusercontent.com/82765301/117499500-5183d600-af49-11eb-985f-32be72ac72e8.png">

**Comment by ryadaj** [comment]
Actually I added a space between the IDs and the next block and now it works perfectly. Thanks so much for this!! :)

**Comment by raddevon** [comment]
I'm still having this problem. I have this template:

    —-
    start-time: 2021-07-17T10:34:33.278-07:00
    medium: Skype
    ---
    
    Cmd-E to edit this call log
    
    
    
    ```button
    name End Call
    type line(3) template
    action call end time
    templater true
    color red
    remove true
    ```
    ^button-xiwo

The button renders properly. Clicking the button inserts the template and processes the templater commands. The button is not removed though. It flashes as though it's being removed and re-added, but I'm not clear why.

Is this related, or should I open a new issue?
